version: 0.0
os: linux
files:
  - source: frontend/
    destination: /home/ec2-user/frontend

  - source: backend/
    destination: /home/ec2-user/backend


hooks:
  BeforeInstall:
    - location: /home/ec2-user/scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: /home/ec2-user/scripts/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: /home/ec2-user/scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: /home/ec2-user/scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
